##############################################
############ Path configuration ##############
##############################################

path:
    fastq: ['fastq/']
    log: 'log/'
    qc: 'data/RNA_seq/qc/'
    bam: 'data/RNA_seq/bams/'
    out: 'data/RNA_seq/output/'
    star: 'STARindex/'
    fa_star: 'STARindex/fasta/'
    gtf_star: 'STARindex/gtf/'


##############################################
############ Software options ################
##############################################

ftcount:
    threads: 20

trim:
    params:
        trimmer: "TRAILING:3" # Cut bases off the end of a read, if below a threshold quality; use LEADING for begining
    threads: 4
    #For more options check the manual @ http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf

star:
    threads: 15

bam:
    params: '-b -h -q20' 
    #-b Output in the BAM format.
    #-h Include the header in the output.
    #-qINT Skip alignments with MAPQ smaller than INT [0]
    #For more options check the manual @ http://www.htslib.org/doc/samtools.html
